services:
  traefik:
    image: traefik:3.1
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web777.address=:777"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=$${APP_ENV==prod}"
      - "--entrypoints.websecure.http3=$${APP_ENV==prod}"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=$${APP_ENV==prod}"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=$${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8080:8080"
      - "777:777"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    environment:
      - DOMAIN=${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - APP_ENV=${APP_ENV}
    networks:
      - private
      - traefik

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    labels:
      - "traefik.enable=true"
      # config 1 (port 80)
      - "traefik.http.routers.nginx-80.rule=Host(`${DOMAIN}`) || Host(`localhost`)"
      - "traefik.http.routers.nginx-80.entrypoints=web"
#      - "traefik.http.routers.nginx-80.entrypoints=websecure"
#      - "traefik.http.routers.nginx-80.tls=true"
#      - "traefik.http.routers.nginx-80.tls.certresolver=letsencrypt"
      - "traefik.http.services.nginx-80.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx-80.service=nginx-80"
      # config 2 (port 777)
      - "traefik.http.routers.nginx-777.rule=Host(`nginxtest.loc`) || Host(`localhost`)"
      - "traefik.http.routers.nginx-777.entrypoints=web777"
      - "traefik.http.services.nginx-777.loadbalancer.server.port=777"
      - "traefik.http.routers.nginx-777.service=nginx-777"
    volumes:
      - ./.docker/nginx/myTemplates:/etc/nginx/myTemplates
      # Copy all additional sites to Nginx container
      - ./.docker/nginx/sites:/etc/nginx/sites-enabled
      # Main site (for nginx config)
      - ${PROJECT_DIR_IN_HOST}/:${PROJECT_DIR_IN_DOCKER}
      # Another sites for future (for nginx config)
      - /var/www:/var/www:rw
      - ./.docker/nginx/start-nginx.sh:/start-nginx.sh
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - DOMAIN=${DOMAIN:-localhost}
    command: sh /start-nginx.sh
    networks:
      - private
      - traefik

  php-fpm:
    build:
      dockerfile: .docker/php-fpm-alpine/Dockerfile
    volumes:
      - ${PROJECT_DIR_IN_HOST}/:${PROJECT_DIR_IN_DOCKER}
      # Another sites for future (for nginx config)
      - /var/www:/var/www:rw
    environment:
      PHP_IDE_CONFIG: "serverName=myLepp"
      APP_ENV: ${APP_ENV}
      APP_URL: ${APP_URL}
      APP_SECRET: ${APP_SECRET}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      AKISMET_KEY: ${AKISMET_KEY}
      SLACK_DSN: ${SLACK_DSN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    depends_on:
      - db
    networks:
      - private
      - traefik

#  db:
#    image: mysql:5.7
#    environment:
#      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - db_lepp_mysql:/var/lib/mysql
#    ports:
#      - "33066:3306"
#    networks:
#      - private
#      - traefik

  db:
    image: postgres:16.2-bookworm
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_lepp:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    networks:
      - private
      - traefik

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - private
      - traefik
  ###< symfony/mailer ###

networks:
  private:
    internal: true
  traefik:
    external: true

volumes:
  db_lepp:
  db_lepp_mysql:
